# -*- coding: utf-8 -*-
"""VSEC 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enXh_t3VsL9B9ND-g11QdPGb2wuG0UfC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/student-mat.csv")

df.head()

df=pd.read_csv("/content/dataset.csv.csv")

df.head()